import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/theme/theme-provider";

const iranSans = localFont({
  src: [
    {
      path: "/fonts/IRANSansWebFaNum-Light.woff2",
      style: "normal",
    },
    {
      path: "/fonts/IRANSansXFaNum-Medium.woff2",
      style: "normal",
    },
  ],
  variable: "--font-iransans",
  display: "swap",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa" dir="rtl"
      className=" h-full antialiased " suppressHydrationWarning    >

      <body className={iranSans.variable}>
        <ThemeProvider>
          <Toaster />
          {children}
        </ThemeProvider>
      </body>

    </html>
  );
}
